const router = require('express').Router();
const PDFDocument = require('pdfkit');
const Plan = require('../models/Plan');
const { verifyToken } = require('../middleware/auth');

router.get('/:id/export', verifyToken, async (req, res) => {
  try {
    const plan = await Plan.findOne({
      _id: req.params.id,
      userId: req.user.id
    });
    if (!plan) return res.status(404).json({ error: 'Plan not found.' });

    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="EventIQ-${plan._id}.pdf"`);
    doc.pipe(res);

    // Header
    doc.fontSize(26).font('Helvetica-Bold').fillColor('#1d1d1f')
      .text('EventIQ', 50, 50);
    doc.fontSize(10).font('Helvetica').fillColor('#6e6e73')
      .text('AI-powered event planning', 50, 82);
    doc.moveTo(50, 100).lineTo(545, 100).strokeColor('#d2d2d7').lineWidth(0.5).stroke();

    // Title
    doc.moveDown(1.5).fontSize(18).font('Helvetica-Bold').fillColor('#1d1d1f')
      .text(plan.title, { width: 495 });

    // Date
    doc.fontSize(10).font('Helvetica').fillColor('#6e6e73')
      .text(`Saved: ${new Date(plan.createdAt).toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}`)
      .moveDown(1);

    // Content — strip HTML tags for clean PDF text
    const cleanContent = (plan.content || '')
      .replace(/<div class="cost-row total">/gi, '\n--- TOTAL ---\n')
      .replace(/<div class="cost-row">/gi, '\n')
      .replace(/<span class="item">/gi, '')
      .replace(/<span class="price">/gi, '  →  ')
      .replace(/<\/span>/gi, '')
      .replace(/<\/div>/gi, '')
      .replace(/<p>/gi, '\n')
      .replace(/<\/p>/gi, '')
      .replace(/<strong>/gi, '')
      .replace(/<\/strong>/gi, '')
      .replace(/<ul>/gi, '\n')
      .replace(/<li>/gi, '• ')
      .replace(/<\/li>/gi, '\n')
      .replace(/<\/ul>/gi, '')
      .replace(/<[^>]+>/gi, '')
      .replace(/&amp;/g, '&')
      .replace(/&lt;/g, '<')
      .replace(/&gt;/g, '>')
      .replace(/\n{3,}/g, '\n\n')
      .trim();

    doc.fontSize(11).font('Helvetica').fillColor('#1d1d1f')
      .text(cleanContent, { width: 495, lineGap: 4 });

    // Footer
    doc.fontSize(8).fillColor('#aeaeb2')
      .text(
        `Generated by EventIQ · ${new Date().toLocaleDateString('en-IN')} · Costs are estimates only.`,
        50, doc.page.height - 40,
        { align: 'center', width: 495 }
      );

    doc.end();
  } catch (err) {
    console.error('PDF export error:', err);
    if (!res.headersSent) {
      res.status(500).json({ error: 'Failed to generate PDF.' });
    }
  }
});

module.exports = router;